### ISSUE TITLE
提示URI错误

### ISSUE THREAD

**Issue by Calx-Takeno** [Hello-Mango/MTopSdkSMS.Core#1]
首先感谢作者提供了这么一个SDK解决.NET CORE的痛苦，但是在集成时候遇到些问题希望得到帮助，"Domain": "dysmsapi.aliyuncs.com"，根据大鱼的官方文档，URL应该是这个，但是现在提示这个

Invalid URI: The format of the URI could not be determined.

   at Top.Api.DefaultTopClient.DoExecute[T](ITopRequest`1 request, String session, DateTime timestamp)
   at Top.Api.DefaultTopClient.Execute[T](ITopRequest`1 request, String session)

**Comment by Hello-Mango** [comment]
url我们用的是这个http://gw.api.taobao.com/router/rest，你可以试试
